apiVersion: v1
kind: Service
metadata:
  name: sample-java-app-service
  labels:
    app: sample-java-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: sample-java-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-java-app-nodeport
  labels:
    app: sample-java-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: sample-java-app